name: custom_image_crop
description: A new Flutter package project.
version: 0.0.1
author: icapps
homepage: icapps.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gesture_x_detector: ^0.0.5
  # image: ^2.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

