name: custom_image_crop
description: An image cropper that is customizable
version: 0.0.1
homepage: https://github.com/icapps/flutter-custom-image-crop

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gesture_x_detector: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

